# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test7_1A.h \
    ./LoginDlg.h
SOURCES += ./LoginDlg.cpp \
    ./main.cpp \
    ./Test7_1A.cpp
FORMS += ./LoginDlg.ui \
    ./Test7_1A.ui
RESOURCES += Test7_1A.qrc
